name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkout:
    name: Checkout do Código
    runs-on: ubuntu-latest

    steps:
      - name: Iniciando fase de checkout
        run: echo "Iniciando fase de checkout do código"

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Exibir estrutura do projeto
        run: |
          echo "Exibindo estrutura do projeto"
          pwd
          ls -R
          echo "Estrutura do projeto verificada"

  setup-python:
    name: Configurar Python
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Iniciando configuração do Python
        run: echo "Iniciando configuração do ambiente Python"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar versões
        run: |
          echo "Verificando versões do Python e pip"
          python --version
          pip --version

      - name: Instalar dependências básicas
        run: |
          echo "Instalando dependências básicas"
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

  lint:
    name: Verificar Código (Linting)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Iniciando fase de linting
        run: echo "Iniciando verificação de código (Linting)"

      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar Código (Linting)
        run: |
          echo "Executando ferramentas de linting"
          python -m pip install --upgrade pip
          black --check src/ tests/ || true
          flake8 src/ tests/ || true
          mypy src/ || true
          pylint src/ || true

  test:
    name: Executar Testes Unitários
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.10']
    needs: setup-python

    steps:
      - name: Iniciando fase de testes
        run: echo "Iniciando execução de testes unitários em ${{ matrix.os }}"

      - uses: actions/checkout@v4

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependências
        run: |
          echo "Instalando dependências para testes"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Executar testes (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Executando testes no Windows"
          python -m pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=html
        continue-on-error: true

      - name: Executar testes (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "Executando testes no macOS"
          python -m pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=html
        continue-on-error: true

      - name: Executar testes (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "Executando testes em sistemas Unix"
          pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=html
        continue-on-error: true


      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ runner.os }}
          path: |
            coverage.xml
            htmlcov/

  finalize:
    name: Finalizar Pipeline
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Iniciando fase de finalização
        run: echo "Iniciando fase de finalização da pipeline"

      - name: Verificar Resultados
        run: |
          echo "Pipeline executada com sucesso em todos os sistemas operacionais"
          echo "Linting e testes completados"
