name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkout:
    name: Checkout do Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Exibir estrutura do projeto
        run: |
          pwd
          tree -L 3

  setup-python:
    name: Configurar Python
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configurar ambiente virtual
        run: |
          python -m venv .venv
          echo "Ambiente virtual criado com sucesso!"

      - name: Ativar ambiente virtual e instalar dependências
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install pytest flake8 black mypy coverage

      - name: Gerar requirements.txt se não existir
        run: |
          source .venv/bin/activate
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt não encontrado. Gerando arquivo..."
            pip freeze > requirements.txt
          fi

      - name: Verificar existência de requirements.txt
        run: |
          source .venv/bin/activate
          if [ ! -f requirements.txt ]; then
            echo "Arquivo requirements.txt não encontrado, mas o pipeline continuará."
          fi

  lint:
    name: Análise de Código (Flake8)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Verificar linting com Flake8
        run: |
          source .venv/bin/activate
          flake8 src . --count --show-source --statistics

  format:
    name: Verificar Formatação (Black)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Verificar formatação com Black
        run: |
          source .venv/bin/activate
          black --check src .

  type-check:
    name: Análise Estática (MyPy)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Verificar tipagem com MyPy
        run: |
          source .venv/bin/activate
          mypy src --ignore-missing-imports

  test:
    name: Executar Testes Unitários (Pytest)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Executar testes com Pytest
        run: |
          source .venv/bin/activate
          pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=term

  publish-report:
    name: Publicar Relatórios de Testes
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Publicar Relatórios de Testes
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.xml

      - name: Publicar Relatório de Cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
