name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkout:
    name: Checkout do Código
    runs-on: ubuntu-latest
    outputs:
      python-version: '3.10'

    steps:
      - name: Iniciando fase de checkout
        run: echo "Iniciando fase de checkout do código"

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Exibir estrutura do projeto
        run: |
          echo "Exibindo estrutura do projeto"
          pwd
          ls -R
          echo "Estrutura do projeto verificada"

  setup-python:
    name: Configurar Python e Instalar Dependências
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Iniciando configuração do ambiente Python
        run: echo "Iniciando configuração do ambiente Python"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.checkout.outputs.python-version }}

      - name: Verificar versões
        run: |
          echo "Verificando versões do Python e pip"
          python --version
          pip --version

      - name: Instalar dependências básicas
        run: |
          echo "Instalando dependências básicas"
          python -m pip install --upgrade pip
          pp freeze > requirements.txt
          pip install -r requirements.txt
          pip install pytest pytest-cov

  lint:
    name: Verificar Código (Linting)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Iniciando fase de linting
        run: echo "Iniciando verificação de código (Linting)"

      - name: Verificar Código (Linting)
        run: |
          echo "Executando ferramentas de linting"
          black --check src/ tests/ || true
          flake8 src/ tests/ || true
          mypy src/ || true
          pylint src/ || true

  test:
    name: Executar Testes Unitários
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.10']
    needs: setup-python

    steps:
      - name: Iniciando fase de testes
        run: echo "Iniciando execução de testes unitários em ${{ matrix.os }}"

      - name: Instalar dependências para testes
        run: |
          echo "Instalando dependências para testes"
          python -m pip install --upgrade pip
          pp freeze > requirements.txt
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Executar testes
        run: |
          echo "Executando testes no ${{ matrix.os }}"
          python -m pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ runner.os }}
          path: |
            coverage.xml
            htmlcov/

  finalize:
    name: Finalizar Pipeline
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Iniciando fase de finalização
        run: echo "Iniciando fase de finalização da pipeline"

      - name: Verificar Resultados
        run: |
          echo "Pipeline executada com sucesso em todos os sistemas operacionais"
          echo "Linting e testes completados"
          echo "Verificando resultados dos testes"
          if [ -f "report.xml" ]; then
            echo "Relatório de testes encontrado"
            cat report.xml
          else
            echo "Relatório de testes não encontrado"
          fi

      - name: Notificar Conclusão
        run: |
          echo "Pipeline concluída com sucesso"
          echo "Notificando conclusão da pipeline"
          # Aqui você pode adicionar comandos para enviar notificações, como Slack, email, etc.
