name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkout:
    name: Checkout do Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Exibir estrutura do projeto
        run: |
          pwd
          tree -L 3

  setup-python:
    name: Configurar Python
    runs-on: ubuntu-22.04
    needs: checkout

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar versões do Python e Pip
        run: |
          python --version
          pip --version

      - name: Configurar ambiente virtual e instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || echo "Ignorando erros de instalação..."
          pip install pytest flake8 black mypy pylint coverage pytest-cov || echo "Ignorando erros de instalação..."
          echo "Dependências instaladas com sucesso"

      - name: Validar dependências instaladas
        run: |
          pip freeze

  lint:
    name: Verificar Código (Linting)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Configurar ambiente virtual
        run: |
          source venv/bin/activate
          pip install flake8 black pylint mypy || echo "Ignorando erros de instalação..."

      - name: Verificar formatação com Black
        run: |
          source venv/bin/activate
          black --check .

      - name: Verificar estilo com Flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Verificar código com Pylint
        run: |
          source venv/bin/activate
          pylint src/

      - name: Verificar tipos com Mypy
        run: |
          source venv/bin/activate
          mypy src/

  test:
    name: Executar Testes Unitários (Pytest)
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente virtual e instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest pytest-cov
          pip freeze > requirements.txt
          pip install -r requirements.txt

      - name: Executar testes com Pytest
        run: |
          source venv/bin/activate
          pytest tests/ --junitxml=report.xml --cov=src --cov-report=xml --cov-report=term

      - name: Verificar a existência do arquivo de relatório
        run: |
          ls -l report.xml || echo "report.xml não encontrado"
          ls -l coverage.xml || echo "coverage.xml não encontrado"

      - name: Validar formato do relatório de testes
        run: |
          if [ ! -f report.xml ]; then
            echo "Erro: report.xml não foi gerado."
            exit 1
          fi
          if [ ! -f coverage.xml ]; then
            echo "Erro: coverage.xml não foi gerado."
            exit 1
          fi

      - name: Publicar Relatório de Testes
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.xml

      - name: Publicar Relatório de Cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  post-deployment:
    name: Pós-Implantação (Verificações Finais)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Verificar a versão do Python novamente após os testes
        run: |
          python --version

      - name: Realizar verificações de permissões e integridade
        run: |
          ls -ld venv
          ls -l report.xml
          ls -l coverage.xml
