name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkout:
    name: Checkout do código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar estrutura de diretórios
        run: |
          pwd
          ls -l

  setup-python:
    name: Configurar Python
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

  lint:
    name: Verificar linting com Flake8
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Verificar linting com Flake8
        run: |
          flake8 .

  format:
    name: Verificar formatação com Black
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Verificar formatação com Black
        run: |
          black --check .

  test:
    name: Executar testes com Pytest
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
      - name: Executar testes com Pytest
        run: |
          pytest tests/ --junitxml=report.xml

  publish-report:
    name: Publicar Relatórios de Testes
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Publicar Relatórios de Testes
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.xml
